logo:
  #nav_mobile: images/logo-apollo-space-left.svg
  #subbrand: images/logo-apollo-subbrands-developers-space.svg
  title: Vulcan Documentation
  subtitle: Vulcan Documentation
  url: http://docs.vulcanjs.org/
favicon: images/favicon.ico

nav_links:
  'GitHub':
    url: https://github.com/vulcanjs/vulcan
  'Slack':
    url: http://slack.vulcanjs.org

